# Generated by Django 5.2.13 on 2026-06-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_multilang'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Unique views'),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='blogs.post')),
            ],
            options={
                'verbose_name': 'Post view',
                'verbose_name_plural': 'Post views',
                'constraints': [models.UniqueConstraint(fields=('post', 'visitor_key'), name='unique_post_visitor')],
            },
        ),
    ]
